### ISSUE TITLE
URL in Community HTML is invalid

### ISSUE THREAD

**Issue by SISheogorath** [freifunk/viewer.api.freifunk.net#3]
The URL in community.html is invalid (as example http://api-viewer.freifunk.net/fulda.html).

```
<a href="http://https://fulda.freifunk.net">https://fulda.freifunk.net</a>
```

The [Specs](https://github.com/freifunk/api.freifunk.net/blob/master/specs/0.4.9.json#L161-L166) say URL with http or https.

**Comment by andibraeu** [comment]
seems to be working
